import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const suggestions = [
  // ── Thailand (10) ────────────────────────────────────────────────
  {
    destination: 'Thailand',
    title: 'טיול בבנגקוק',
    description: 'גלו את בירתתאילנד התוססת — מקדשים מרהיבים, שווקים תוססים ואוכל רחוב מדהים.',
    category: 'עיר',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bangkok',
    lat: 13.7563,
    lng: 100.5018,
    rating: 4.5,
    tags: ['עיר', 'תרבות', 'אוכל'],
  },
  {
    destination: 'Thailand',
    title: 'חופי פוקט',
    description: 'חופי חול לבן ומים טורקיז באחם יפים בעולם. מושלם למשפחות עם ילדים.',
    category: 'חוף',
    imageUrl: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Phuket',
    lat: 7.8804,
    lng: 98.3923,
    rating: 4.7,
    tags: ['חוף', 'שקיעה', 'משפחות'],
  },
  {
    destination: 'Thailand',
    title: 'צפיה בפילים בצ\'יאנג מאי',
    description: 'פארק טבע מוגן עם פילים בסביבה טבעתית. חוויה בלתי נשכחת לכל המשפחה.',
    category: 'טבע',
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Chiang_Mai',
    lat: 18.7883,
    lng: 98.9853,
    rating: 4.3,
    tags: ['טבע', 'חיות', 'הרים'],
  },
  {
    destination: 'Thailand',
    title: 'אי פי פי',
    description: 'אי טרופי מדהים עם צוקים אבן גיר ומפרצים כחולים. אידיאלי לצלילה וסנורקלינג.',
    category: 'אי',
    imageUrl: 'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ko_Phi_Phi',
    lat: 7.7411,
    lng: 98.7784,
    rating: 4.6,
    tags: ['אי', 'צלילה', 'ים'],
  },
  {
    destination: 'Thailand',
    title: 'שוק הכביש קאו סאן',
    description: 'שוק הרחוב המפורסם ביותר בבנגקוק — קניות, אוכל רחוב ואווירה ייחודית.',
    category: 'קניות',
    imageUrl: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Khao_San_Road',
    lat: 13.7589,
    lng: 100.4975,
    rating: 4.2,
    tags: ['קניות', 'אוכל', 'לילה'],
  },
  {
    destination: 'Thailand',
    title: 'מקדש הבודהה האמרלדי',
    description: 'אחד המקדשים המרהיבים בעולם, ממוקם בלב בנגקוק. חוויה רוחנית ותרבותית.',
    category: 'תרבות',
    imageUrl: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Wat_Phra_Kaew',
    lat: 13.7514,
    lng: 100.4926,
    rating: 4.8,
    tags: ['תרבות', 'מקדש', 'היסטוריה'],
  },
  {
    destination: 'Thailand',
    title: 'נהר קוואי',
    description: 'רפטינג על הנהר בין גושי ג\'ונגל מרהיבים. הרפתקה מושלמת למשפחות.',
    category: 'הרפתקה',
    imageUrl: 'https://images.unsplash.com/photo-1540611025311-01df3cef54b5?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/River_Kwai',
    lat: 14.0167,
    lng: 99.5333,
    rating: 4.4,
    tags: ['הרפתקה', 'נהר', 'טבע'],
  },
  {
    destination: 'Thailand',
    title: 'פטאיה',
    description: 'עיר חוף תוססת עם בתי מלון, מסעדות ובילויים לכל המשפחה.',
    category: 'עיר',
    imageUrl: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pattaya',
    lat: 12.9236,
    lng: 100.8825,
    rating: 4.0,
    tags: ['עיר', 'חוף', 'בילוי'],
  },
  {
    destination: 'Thailand',
    title: 'קרב תאילנדי',
    description: 'חוויה ייחודית — צפייה בקרב תאילנדי אותנטי. כיף לכל הגילאים.',
    category: 'בידור',
    imageUrl: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Muay_Thai',
    lat: 13.7563,
    lng: 100.5018,
    rating: 4.1,
    tags: ['ספורט', 'תרבות', 'בידור'],
  },
  {
    destination: 'Thailand',
    title: 'סופרי תאילנדי',
    description: 'סדנת בישול תאילנדית אותנטית. למדו להכין פד תאי וקארי ירוק ביתי.',
    category: 'אוכל',
    imageUrl: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Thai_cuisine',
    lat: 13.7563,
    lng: 100.5018,
    rating: 4.6,
    tags: ['אוכל', 'סדנה', 'תרבות'],
  },

  // ── Japan (10) ───────────────────────────────────────────────────
  {
    destination: 'Japan',
    title: 'טוקיו — עיר האורות',
    description: 'המטרופולין הגדול בעולם — שילוב ייחודי של מסורת וטכנולוגיה עתידנית.',
    category: 'עיר',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Tokyo',
    lat: 35.6762,
    lng: 139.6503,
    rating: 4.8,
    tags: ['עיר', 'טכנולוגיה', 'תרבות'],
  },
  {
    destination: 'Japan',
    title: 'הר פוג\'י',
    description: 'טיול להר המקודש פוג\'י — נוף פנורמי מרהיב וחוויה רוחנית.',
    category: 'טבע',
    imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mount_Fuji',
    lat: 35.3606,
    lng: 138.7274,
    rating: 4.9,
    tags: ['הר', 'טבע', 'פנורמה'],
  },
  {
    destination: 'Japan',
    title: 'קיוטו — עיר המקדשים',
    description: 'מאות מקדשים בודהיסטיים, גנים יפים וארכיטקטורה מסורתית מרהיבה.',
    category: 'תרבות',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kyoto',
    lat: 35.0116,
    lng: 135.7681,
    rating: 4.7,
    tags: ['תרבות', 'מקדש', 'היסטוריה'],
  },
  {
    destination: 'Japan',
    title: 'אוסקה',
    description: 'עיר האוכל היפנית — טאקויאקי, אוקונומיאקי וחיי לילה תוססים.',
    category: 'עיר',
    imageUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Osaka',
    lat: 34.6937,
    lng: 135.5023,
    rating: 4.5,
    tags: ['עיר', 'אוכל', 'בידור'],
  },
  {
    destination: 'Japan',
    title: 'איינשטיין מוזיאון טוקיו',
    description: 'מוזיאון מדע אינטראקטיבי מדהים לכל המשפחה. כיף ולמידה ביחד.',
    category: 'מוזיאון',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Miraikan',
    lat: 35.6191,
    lng: 139.7742,
    rating: 4.4,
    tags: ['מוזיאון', 'ילדים', 'מדע'],
  },
  {
    destination: 'Japan',
    title: 'אנטרטיקה טוקיו',
    description: 'פארק שעשועים מתחת לאדמה עם אטרקציות מדהימות לכל הגילאים.',
    category: 'בידור',
    imageUrl: 'https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Tokyo_Dome_City',
    lat: 35.7101,
    lng: 139.7514,
    rating: 4.3,
    tags: ['בידור', 'ילדים', 'פארק'],
  },
  {
    destination: 'Japan',
    title: 'ניקקו',
    description: 'עיר מקדשים מרהיבה בהרים — יער שדרות, מקדשים מזוזזים ונופים קסומים.',
    category: 'תרבות',
    imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Nikko_(Tochigi)',
    lat: 36.7199,
    lng: 139.6982,
    rating: 4.6,
    tags: ['תרבות', 'הרים', 'מקדש'],
  },
  {
    destination: 'Japan',
    title: 'הירושימה',
    description: 'מוזיאון השלום והפסיפס הזכוכית — חוויה היסטורית מרגשת וחינוכית.',
    category: 'היסטוריה',
    imageUrl: 'https://images.unsplash.com/photo-1573160103600-9e1dfe7af7df?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Hiroshima_Peace_Memorial',
    lat: 34.3955,
    lng: 132.4536,
    rating: 4.8,
    tags: ['היסטוריה', 'שלום', 'חינוך'],
  },
  {
    destination: 'Japan',
    title: 'אוקינאווה',
    description: 'איים טרופיים עם חופים מדהימים, שוניות אלמוגים ותרבות ריוקיו ייחודית.',
    category: 'אי',
    imageUrl: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Okinawa',
    lat: 26.3344,
    lng: 127.8056,
    rating: 4.5,
    tags: ['אי', 'חוף', 'צלילה'],
  },
  {
    destination: 'Japan',
    title: 'סושי בצ\'ואו',
    description: 'סדנת הכנת סושי מקצועית בלב טוקיו. למדו את האומנות היפנית לבשל.',
    category: 'אוכל',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sushi',
    lat: 35.6722,
    lng: 139.7640,
    rating: 4.7,
    tags: ['אוכל', 'סדנה', 'תרבות'],
  },

  // ── Korea (10) ───────────────────────────────────────────────────
  {
    destination: 'Korea',
    title: 'סיאול — עיר שלא ישנה',
    description: 'הבירה התוססת של דרום קוריאה — ארמונות מלכותיים, קניות וק-פופ.',
    category: 'עיר',
    imageUrl: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Seoul',
    lat: 37.5665,
    lng: 126.978,
    rating: 4.6,
    tags: ['עיר', 'קניות', 'תרבות'],
  },
  {
    destination: 'Korea',
    title: 'אי ג\'אג\'ו',
    description: 'אי קסום עם חופים, שבילי הליכה ונופים מרהיבים. מושלם לזוגות ומשפחות.',
    category: 'אי',
    imageUrl: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Jeju_Island',
    lat: 33.4996,
    lng: 126.5312,
    rating: 4.7,
    tags: ['אי', 'טבע', 'חוף'],
  },
  {
    destination: 'Korea',
    title: 'פוסאן',
    description: 'עיר נמל עם שווקי דגים מדהימים, חופים ותרבות קוריאנית אותנטית.',
    category: 'עיר',
    imageUrl: 'https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Busan',
    lat: 35.1796,
    lng: 129.0756,
    rating: 4.4,
    tags: ['עיר', 'דגים', 'חוף'],
  },
  {
    destination: 'Korea',
    title: 'ארמון קיונבוק',
    description: 'ארמון מלכותי מהמאה ה-14 — ארכיטקטורה קוריאנית מסורתית מרהיבה.',
    category: 'תרבות',
    imageUrl: 'https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Gyeongbokgung',
    lat: 37.5796,
    lng: 126.977,
    rating: 4.5,
    tags: ['תרבות', 'היסטוריה', 'ארמון'],
  },
  {
    destination: 'Korea',
    title: 'קוריאן ביבימבאפ',
    description: 'סדנת בישול קוריאנית — למדו להכין ביבימבאפ, קימצ\'י וקלאסיקות קוריאניות.',
    category: 'אוכל',
    imageUrl: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Korean_cuisine',
    lat: 37.5665,
    lng: 126.978,
    rating: 4.6,
    tags: ['אוכל', 'סדנה', 'תרבות'],
  },
  {
    destination: 'Korea',
    title: 'פארק לוט וורלד',
    description: 'פארק שעשועים ענק עם אטרקציות לכל הגילאים — אחד הגדולים בעולם.',
    category: 'בידור',
    imageUrl: 'https://images.unsplash.com/photo-1580826828658-4156c713c79f?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Lotte_World',
    lat: 37.5111,
    lng: 127.098,
    rating: 4.3,
    tags: ['בידור', 'ילדים', 'פארק'],
  },
  {
    destination: 'Korea',
    title: 'דמורת הגבול DMZ',
    description: 'ביקור באזור ההפרדה בין צפון לדרום קוריאה — חוויה היסטורית ייחודית.',
    category: 'היסטוריה',
    imageUrl: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Korean_Demilitarized_Zone',
    lat: 37.956,
    lng: 126.677,
    rating: 4.2,
    tags: ['היסטוריה', 'חינוך', 'גבול'],
  },
  {
    destination: 'Korea',
    title: 'ג\'וג\'ון — כפר ההיסטורי',
    description: 'כפר מסורתי קוריאני — חוויה של חיי היומיום בקוריאה העתיקה.',
    category: 'תרבות',
    imageUrl: 'https://images.unsplash.com/photo-1583415088484-1d2b681f309e?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Jeonju_Hanok_Village',
    lat: 35.8242,
    lng: 127.148,
    rating: 4.4,
    tags: ['תרבות', 'היסטוריה', 'כפר'],
  },
  {
    destination: 'Korea',
    title: 'סונגוון',
    description: 'רובע הבילויים המפורסם בסיאול — קייפהאוסים, קריוקי וחיי לילה.',
    category: 'בידור',
    imageUrl: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Hongdae_(area)',
    lat: 37.5563,
    lng: 126.922,
    rating: 4.1,
    tags: ['בידור', 'לילה', 'קייפהוס'],
  },
  {
    destination: 'Korea',
    title: 'הר סוראקסן',
    description: 'פארק לאומי עם נופים דרמטיים, מסלולי הליכה ועלים בצבעי סתיו.',
    category: 'טבע',
    imageUrl: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=800',
    sourceUrl: 'https://en.wikipedia.org/wiki/Seoraksan',
    lat: 38.1195,
    lng: 128.4655,
    rating: 4.8,
    tags: ['טבע', 'הר', 'הליכה'],
  },
];

async function main() {
  console.log('🌱 Seeding suggestions...');

  // Clear existing
  await prisma.suggestion.deleteMany();

  for (const s of suggestions) {
    await prisma.suggestion.create({ data: s });
  }

  const count = await prisma.suggestion.count();
  console.log(`✅ Seeded ${count} suggestions`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
